#!/bin/bash
#
# NOTE! DO NOT RUN THIS SCRIPT MORE THAN ONCE A DAY
#
# See limitation notice on
# https://regauth.standards.ieee.org/standards-ra-web/pub/view.html
if [[ $(find lastupdate.go -type f -newermt $(date --date="today" "+%Y-%m-%d")) ]]
then
    echo "already updated today, skip!"
    exit 0
fi

wget https://standards-oui.ieee.org/oui/oui.csv
mv oui.csv mal.csv

wget https://standards-oui.ieee.org/oui28/mam.csv
mv mam.csv.1 mam.csv

wget https://standards-oui.ieee.org/oui36/oui36.csv
mv oui36.csv mas.csv

echo "// GENERATED by update.sh, DO NOT EDIT!
package source

const LastUpdate string = \"$(date '+%Y-%m-%d')\"" > lastupdate.go

